<a href="https://colab.research.google.com/github/martha-irungu/martha-projects/blob/master/Python_Notebook_WK_4_1P_Martha_Irungu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Moringa Data Science Prep IP: Week 4


Question

 An electric car-sharing service company has tasked me to process stations data to understand electric car usage over time by solving  the following research questions;

Research Question/s

Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.
Bonus Questions (Optional)

What is the most popular hour for returning cars?
What station is the most popular?
Overall?
At the most popular picking hour?
What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
Overall?
At the most popular picking hour?
Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars? 

Datasets Provided

[http://bit.ly/autolib_dataset]


[Link] (Links to an external site.)-Document with the details of the dataset


Importing our libraries

In [0]:
import pandas as pd

import numpy as np


Loading our Datasets

In [3]:
# loading & previewing data set
df = pd.read_csv('Autolib_dataset.csv')
df.head()


Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

Data Exploration

In [4]:
# previewing basic information of our dataset
df.info()
df.shape


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64 
 2   Bluecar counter      5000 non-null   int64 
 3   Utilib counter       5000 non-null   int64 
 4   Utilib 1.4 counter   5000 non-null   int64 
 5   Charge Slots         5000 non-null   int64 
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64 
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots 

(5000, 25)

In [5]:
# To count the number of non - missing values in the df dataframe
#
df.count()

Address                5000
Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
Displayed comment       111
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Scheduled at             47
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
year                   5000
month                  5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

In [6]:
# To determine the number of missing or null values as shown

num_rows = df.shape[0]
num_missing = num_rows - df.count() 
num_missing

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

Data Cleaning

In [7]:

# Changing columns to lowercase
# Renaming column names 


df.columns = map(str.lower, df.columns)
columns = ['address', 'cars', 'bluecar_counter', 'utilib_counter', 'utilib_1.4_counter','charge_slots', 'charging_status', 'city', 'displayed_comment', 'id', 'kind','geo_point',
           'postal_code','public_name', 'rental_status','scheduled_at','slots','station_type','status','subscription_status','year','month','day','hour', 'minute']
df.columns = columns
df.columns



Index(['address', 'cars', 'bluecar_counter', 'utilib_counter',
       'utilib_1.4_counter', 'charge_slots', 'charging_status', 'city',
       'displayed_comment', 'id', 'kind', 'geo_point', 'postal_code',
       'public_name', 'rental_status', 'scheduled_at', 'slots', 'station_type',
       'status', 'subscription_status', 'year', 'month', 'day', 'hour',
       'minute'],
      dtype='object')

In [8]:
# previewing our dataset
df.head()

address  cars  bluecar_counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [9]:
# dropping duplicates, if any
df = df.drop_duplicates()
df.shape


# After carrying out the function to drop duplicates, there the dataset does not have duplicates as the shape remains the same.

(5000, 25)

In [10]:

# checking for missing values
df.isna().sum()


address                   0
cars                      0
bluecar_counter           0
utilib_counter            0
utilib_1.4_counter        0
charge_slots              0
charging_status           0
city                      0
displayed_comment      4889
id                        0
kind                      0
geo_point                 0
postal_code               0
public_name               0
rental_status             0
scheduled_at           4953
slots                     0
station_type              0
status                    0
subscription_status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [0]:
# Impute missing column with median values
# ---
# 
df.fillna(np.median, inplace = True)


In [12]:
# Checking if the null values have been replaced

df_clean= df.isna().sum()
df_clean

address                0
cars                   0
bluecar_counter        0
utilib_counter         0
utilib_1.4_counter     0
charge_slots           0
charging_status        0
city                   0
displayed_comment      0
id                     0
kind                   0
geo_point              0
postal_code            0
public_name            0
rental_status          0
scheduled_at           0
slots                  0
station_type           0
status                 0
subscription_status    0
year                   0
month                  0
day                    0
hour                   0
minute                 0
dtype: int64

In [14]:

# previewing the unique values in some key of our columns
# address	cars	bluecar_counter	utilib_counter	utilib_1.4_counter	charge_slots	charging_status	city	displayed_comment	id	kind	geo_point	postal_code	public_name	rental_status	scheduled_at	slots	station_type	status	subscription_status	year	month	day	hour	minute


df['address'].unique()



array(['2 Avenue de Suffren', '145 Rue Raymond Losserand',
       '2 Avenue John Fitzgerald Kennedy', ..., '106 rue Vercingétorix',
       '134 boulevard National', '54 Boulevard Sérurier'], dtype=object)

In [15]:
df['cars'].unique()

array([0, 6, 3, 1, 5, 4, 2, 7])

In [16]:
df['bluecar_counter'].unique()

array([0, 6, 3, 1, 5, 4, 2, 7])

In [17]:

df['utilib_counter'].unique()

array([0, 1, 2])

In [18]:
df['charging_status'].unique()

array(['nonexistent', 'operational', 'broken'], dtype=object)

In [30]:
df['city'].unique()

array(['Paris', 'Le Bourget', 'Nanterre', 'Puteaux', 'Fontenay-aux-Roses',
       'Le Chesnay', 'Suresnes', 'Versailles', 'Malakoff',
       'Issy-les-Moulineaux', 'Saint-Cloud', 'Sèvres', 'Bezons',
       'Nogent-sur-Marne', 'Créteil', 'Villejuif', 'Rueil-Malmaison',
       'Villeneuve-la-Garenne', 'Montreuil', 'Charenton-le-Pont',
       'Courbevoie', 'Asnières-sur-Seine', 'Garches', 'Drancy',
       'La Garenne-Colombes', 'Verrières-le-Buisson', 'Le Blanc-Mesnil',
       'Vanves', 'Enghien-les-Bains', 'Sceaux', 'Levallois-Perret',
       'Boulogne-Billancourt', 'Châtenay-Malabry', 'Pantin', 'Meudon',
       'Gennevilliers', 'Vincennes', 'Rungis', 'Colombes',
       'Fontenay-Sous-Bois', 'Rosny-sous-Bois', 'Bourg-la-Reine',
       'Cachan', 'Maisons-Alfort', 'Bièvres', 'Alfortville',
       'Champigny-sur-Marne', 'Aulnay-sous-bois', 'Saint-Denis',
       'Le Plessis-Robinson', 'Le Pré-Saint-Gervais', 'Clamart',
       'Bois-Colombes', 'Guyancourt', 'Bagnolet', 'Vaucresson',
  

In [19]:

df['public_name'].unique()

array(['Paris/Suffren/2', 'Paris/Raymond Losserand/145',
       'Le Bourget/John Fitzgerald Kennedy/2', ...,
       'Paris/Vercingétorix/106', 'Nanterre/National/134',
       'Paris/Sérurier/54'], dtype=object)

In [20]:
df['rental_status'].unique()

array(['operational', 'broken', 'future', 'nonexistent'], dtype=object)

In [44]:

df['displayed_comment'].unique()

array([<function median at 0x7f5222fff598>,
       'Station en parking (niv -1), accès 37 rue Leblanc',
       'Station en parking (niv 0), accès 26 villa Croix Nivert',
       'Station en parking (niv -2), accès 4 av. Foch',
       "Borne d'abonnement en sous-sol (niv -1), accès 4 rue Lobau",
       'Station en parking (niv -1), accès rue Wilson',
       'Station en parking (niv -1), accès Place Georges Pompidou',
       'Station en parking (niv -3), accès 32 rue dâ\x80\x99Alsace',
       'Station en parking (niv -2), accès 2 avenue Gabriel',
       'Station en parking (niv -1), accès av. de Versailles',
       'Station en parking (niv -1), accès rue Abel Gance',
       'Station en parking (niv -1), accès 4 av. des Ternes',
       'Station en parking (niv -1), Station B (sur la droite)',
       'Station en parking',
       'Station en parking (niv -2), accès 125 bvd du Montparnasse',
       'Station en parking (niv -1), Station A (sur la gauche)',
       'Station en parkin

In [45]:

df['id'].unique()

array(['paris-suffren-2', 'paris-raymondlosserand-145',
       'lebourget-johnfitzgeraldkennedy-2', ...,
       'paris-vercingetorix-106', 'nanterre-national-134',
       'paris-serurier-54'], dtype=object)

In [46]:
df['kind'].unique()


array(['STATION', 'PARKING', 'SPACE', 'CENTER'], dtype=object)

In [47]:
df['geo_point'].unique()


array(['48.857, 2.2917', '48.83126, 2.313088', '48.938103, 2.4286035',
       ..., '48.8344374, 2.3137055', '48.88835, 2.184296',
       '48.88075, 2.397629'], dtype=object)

In [48]:
df['postal_code'].unique()

array([75015, 75014, 93350, 75013, 75017, 75011, 92000, 75009, 75005,
       92800, 92260, 78150, 92150, 78000, 92240, 75007, 75010, 92130,
       75006, 75018, 75004, 75020, 92210, 92310, 95870, 94130, 75016,
       94000, 94800, 92500, 75012, 92390, 75003, 93100, 75019, 94220,
       92400, 92600, 92380, 75001, 93700, 92250, 91370, 93150, 75002,
       92170, 75008, 95880, 92330, 92300, 92100, 92290, 93500, 92190,
       92230, 94300, 94150, 92700, 94120, 93110, 92340, 94230, 94700,
       91570, 94140, 94500, 93600, 93200, 92350, 93310, 92140, 92220,
       92270, 78280, 93170, 92420, 94450, 94410, 93230, 78140, 94110,
       75116, 93400, 92360, 92410, 95100, 93130, 94160, 92200, 93390,
       93370, 92160, 93800, 92320, 91330, 93440, 94340, 93360, 92110,
       75112, 92120, 94370, 92370, 91400, 93260, 94100, 93300])

In [49]:
df['scheduled_at'].unique()

array([<function median at 0x7f5222fff598>, '2016-07-27T15:32:21',
       '2016-07-05T13:10:09', '2015-09-29T13:58:29',
       '2016-04-26T14:28:01', '2012-09-17T08:57:28',
       '2016-01-06T10:35:38', '2018-01-03T10:52:00',
       '2016-07-27T15:32:22'], dtype=object)

In [51]:
df['station_type'].unique()

array(['station', 'full_station', 'subs_center'], dtype=object)

In [52]:
df['status'].unique()


array(['ok', 'closed', 'scheduled'], dtype=object)

In [53]:
df['subscription_status'].unique()

array(['nonexistent', 'operational', 'broken'], dtype=object)

Data Analysis

In [24]:
# Question 1;
# Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city 
# of Paris over the month of April 2018.

df.groupby(['hour', 'bluecar_counter','city'])['bluecar_counter'].sum().sort_values(ascending = False)

# The most popular hour was 5th hour 


hour  bluecar_counter  city             
5     5                Paris                95
21    4                Paris                88
10    4                Paris                80
3     5                Paris                80
7     4                Paris                64
                                            ..
11    0                Saint-Mandé          0
                       Paris                 0
                       Neuilly-Plaisance     0
                       Maisons-Alfort        0
0     0                Alfortville           0
Name: bluecar_counter, Length: 2064, dtype: int64

In [0]:
# What is the most popular hour for returning cars?



In [43]:
# What station is the most popular?

df.groupby('public_name')['public_name'].count().sort_values(ascending = False)

# most popular station is Paris/Porte de Montrouge/8

public_name
Paris/Porte de Montrouge/8    13
Paris/Courcelles/69           11
Sèvres/Wolfenbüttel/1       11
Paris/Voltaire/182            11
Paris/Grenelle 31/Parking     11
                              ..
Paris/Lecourbe/336             1
Paris/Porte Pouchet/6          1
Meudon/Ponceau/2               1
Paris/Pirogues de Bercy/44     1
Paris/Jean Veber/3             1
Name: public_name, Length: 1105, dtype: int64

In [27]:
# What postal code is the most popular for picking up Blue cars? 

df.groupby(['postal_code', 'bluecar_counter'])['bluecar_counter'].sum().sort_values(ascending = False)


# 75015 was the most popular postal code for picking Blue cars

postal_code  bluecar_counter
75015        5                  175
75016        4                  172
75015        4                  148
75017        3                  141
75016        5                  140
                               ... 
92700        0                    0
92600        0                    0
92500        0                    0
75112        0                    0
75001        0                    0
Name: bluecar_counter, Length: 641, dtype: int64

In [0]:
# Does the most popular station belong to that postal code?
# Overall?
# At the most popular picking hour?
# Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars? 

In [39]:
df['year','month','day','hour','minute']=pd.to_datetime(df['year']  + df['month']+df['day']+df['hour'] +df['minute'], dayfirst=True) 
df.datetime.head()

# > 0   2019-06-05 14:01:10
# > 1   2019-06-05 14:09:30
# > 2   2019-06-05 14:17:50
# > 3   2019-06-05 14:26:10
# > 4   2019-06-05 14:34:30
# > Name: datetime, dtype: datetime64[ns]

AttributeError: ignored